language: python
python:
  - "3.6"
node_js:
  - "node"
before_install:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.13.tar.gz
  - tar -zxvf libsodium-1.0.13.tar.gz
  - cd libsodium-1.0.13
  - ./configure
  - make && make check
  - sudo make install

install:
  - npm install

script:
  - npm test